# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

env:
  ARM_CLIENT_ID: ${{ secrets.TF_VAR_ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.TF_VAR_ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.TF_VAR_ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.TF_VAR_ARM_TENANT_ID }}   

stages:
  - stage: npm
    jobs:
    - job: build_and_install_node 
      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'
      - script: |
          npm install # download 3rd party libraries
          # npm run build
        displayName: 'npm install and build'
  
  - stage: terraform
    jobs:
      - job: terraform_simple_remote_state_file
        steps:
        - script: |
            echo "Hello World"
            cd terraform
            terraform init
            terraform plan
            terrafrom apply
          displayName: "Terraform Build"
