# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  - someVariable: 'someValue'
  # stored as pipeline secret, however cant read this
  - someSecretVariable: '$(SomeConnectionString)' 
  - TF_VAR_APP_NAME: 'someapp'
  # still need to pass pipline secret as following:
  # -input=false -var "VM_ADMIN_PASSWORD=$(TF_VAR_admin_password)"
  - name: TerraformBackend.ResourceGroup
    value: TF-ResourceGroup
  - name: TerraformBackend.StorageAccount
    value: tfsabob
  - name: TerraformBackend.ContainerName
    value: tfstate

stages:
  - stage: npm
    jobs:
    - job: build_and_install_node 
      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'
      - script: |
          npm install # download 3rd party libraries
          # npm run build
        displayName: 'npm install and build'
  
  - stage: terraform
    jobs:
      - task: TerraformInstaller@0
        displayName: install terraform
        inputs:
          terraformVersion: latest
      - job: terraform_init_validate
        steps:
        - script: |
            echo "Hello World"
            cd terraform
            terraform init
            terraform validate
            terraform plan -input=false -var "VM_ADMIN_PASSWORD=$(TF_VAR_admin_password)"
          displayName: "Terraform Init"
        - task: TerraformTaskV1@0
          displayName: "Terraform Apply"
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'
            environmentServiceNameAzureRM: $(AzureServiceConnection)
            commandOptions: -input=false -var "VM_ADMIN_PASSWORD=$(TF_VAR_admin_password)"